# Generated by Django 2.0.12 on 2022-03-05 19:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0010_auto_20220305_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='course name')),
                ('desc', models.CharField(max_length=300, verbose_name='Course Description')),
                ('detail', models.TextField(verbose_name='Course details')),
                ('degree', models.CharField(choices=[('elementary', 'primary'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=15, verbose_name='grade')),
                ('mode', models.CharField(choices=[('elementary', 'online'), ('intermediate', 'offline')], max_length=15, verbose_name='mode')),
                ('event_time', models.IntegerField(default=0, verbose_name='Duration of Event')),
                ('students', models.IntegerField(default=0, verbose_name='Number of learners')),
                ('category', models.CharField(default='Back-end development', max_length=20, verbose_name='Course category')),
                ('tag', models.CharField(default='', max_length=30, verbose_name='Course tags')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Clicks')),
                ('event_banner', models.CharField(default='', max_length=400, verbose_name='Course notes')),
                ('whatsapp_link', models.CharField(default='', max_length=400, verbose_name='teacher-tells-you')),
                ('is_banner', models.BooleanField(default=False, verbose_name='whether_to_rotate')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.IntegerField(default=0, verbose_name='event price')),
                ('course_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='Course organization')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Event',
            },
        ),
    ]
