# Generated by Django 2.0.12 on 2022-03-05 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(default='Back-end development', max_length=20, verbose_name='Event category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='Event organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=models.TextField(verbose_name='Event details'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_banner',
            field=models.CharField(default='', max_length=400, verbose_name='Event notes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.CharField(default='', max_length=30, verbose_name='Event tags'),
        ),
    ]
