# Generated by Django 2.0.12 on 2021-12-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20200723_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='certified',
            field=models.BooleanField(default=False, verbose_name='certificate provided'),
        ),
    ]
