# Generated by Django 2.0.12 on 2020-07-23 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20180319_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'curriculum', 'verbose_name_plural': 'curriculum'},
        ),
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': 'course_resources', 'verbose_name_plural': 'course_resources'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapter'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Video'},
        ),
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='whether_to_rotate'),
        ),
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='before_diving_in',
            field=models.CharField(default='', max_length=400, verbose_name='Course notes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='Back-end development', max_length=20, verbose_name='Course category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='Clicks'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='Course organization'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('elementary', 'primary'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=15, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(verbose_name='Course details'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='Number of collectors'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/%Y/%m', verbose_name='cover picture'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_time',
            field=models.IntegerField(default=0, verbose_name='Duration of study (minutes)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='course name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=0, verbose_name='Number of learners'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=30, verbose_name='Course tags'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_advice',
            field=models.CharField(default='', max_length=400, verbose_name='teacher-tells-you'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(upload_to='course/resource/%Y%m', verbose_name='Resource'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='chapter_name'),
        ),
        migrations.AlterField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='video',
            name='learning_time',
            field=models.IntegerField(default=0, verbose_name='Duration of study (minutes)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='chapter'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Video name'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='video_link'),
        ),
    ]
