# Generated by Django 2.0.12 on 2021-10-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20211022_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='org/%Y/%m', verbose_name='logo'),
        ),
    ]
