# Generated by Django 2.0.12 on 2022-03-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20211022_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='teachers/%Y/%m', verbose_name='headPortrait'),
        ),
    ]
